### ISSUE TITLE
Does not work, please help

### ISSUE THREAD

**Issue by Dobryash** [niou-ns/homebridge-livolo#1]
Does not work, I tried everything I could do with my mind. 
Homebridge is installed from oznu/docker-homebridge on Raspbian light
Please, help. 

homebridge_1  | [2018-7-30 13:20:01] [Livolo] Initializing Livolo platform...
homebridge_1  | Pin: 17
homebridge_1  | bcm2835_init: Unable to open /dev/gpiomem: No such file or directory
homebridge_1  | 
homebridge_1  | /homebridge/node_modules/rpio/lib/rpio.js:104
homebridge_1  | 	return bindfunc(optarg);
homebridge_1  |         ^
homebridge_1  | Error: Could not initialize bcm2835 GPIO library
homebridge_1  |     at bindcall (/homebridge/node_modules/rpio/lib/rpio.js:104:9)
homebridge_1  |     at EventEmitter.rpio.init (/homebridge/node_modules/rpio/lib/rpio.js:461:2)
homebridge_1  |     at rpio.open (/homebridge/node_modules/rpio/lib/rpio.js:471:18)
homebridge_1  |     at Object.open (/homebridge/node_modules/livolo/index.js:69:10)
homebridge_1  |     at new LivoloPlatform (/homebridge/node_modules/homebridge-livolo/homebridge-livolo.js:34:12)
homebridge_1  |     at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:325:32)
homebridge_1  |     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
homebridge_1  |     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:43:10)
homebridge_1  |     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
homebridge_1  |     at Module._compile (module.js:652:30)

**Comment by niou-ns** [comment]
@Dobryash so did you managed to run it after all?
